name: octodns

on:
  push:
    branches:
      - devel
    paths:
      - .github/workflows/octodns.yml
      - octodns/**

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:

      - name: checkout the code
        uses: actions/checkout@v3

      - name: install python requirements
        run: |
          pip install -r requirements.txt

      - name: octodns dry run
        working-directory: octodns
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          octodns-sync --config-file=config/config.yaml
