name: octodns

on:
  push:
    branches:
      - devel
    paths:
      - .github/workflows/octodns.yml
      - octodns/**
  workflow_dispatch:

jobs:

  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: install python requirements
        run: |
          pip install -r requirements.txt

      - name: octodns dry run
        working-directory: octodns
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          octodns-sync --config-file=config/config.yaml

  ship-it:
    runs-on: ubuntu-latest
    needs: dry-run
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mamercad

      - name: octodns apply
        run: |
          echo octodns apply
