name: octodns

on:
  push:
    branches:
      - devel
    paths:
      - .github/workflows/octodns.yml
      - octodns/**
  workflow_dispatch:

jobs:

  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install python requirements
        run: |
          pip install -r requirements.txt

      - name: octodns dry run
        working-directory: octodns
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          octodns-sync --config-file=config/config.yaml

      # - name: octodns dry run
      #   id: dryrun
      #   uses: mathiasvr/command-output@v1
      #   env:
      #     DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
      #   with:
      #     run: |
      #       cd octodns && octodns-sync --config-file=config/config.yaml

      # - name: output
      #   id: output
      #   run: |
      #     echo "stdout: ${{ steps.dryrun.outputs.stdout }}"
      #     echo "stderr: ${{ steps.dryrun.outputs.stderr }}"

  ship-it:
    runs-on: ubuntu-latest
    needs: dry-run
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mamercad
          # minimum-approvals: 1
          # issue-title: Deploy OctoDNS changes

      - name: octodns apply
        run: |
          octodns-sync --config-file=config/config.yaml --doit
