name: pulumi-preview

on:
  push:
    branches:
      - devel
    paths:
      - .github/workflows/pulumi-preview.yml
      - pulumi/**

jobs:
  preview:
    name: preview
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: pip install -r requirements.txt
        working-directory: pulumi

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
